### ISSUE TITLE
Correctness Issue.

### ISSUE THREAD

**Issue by piyush121** [payamrastogi/Questions#62]
Hi Payam,
Found a small issue in :
https://github.com/payamrastogi/Questions/blob/master/Algo/Java/ArrayRotation.java

My Input is:

`int[] arr = {1, 2, 3};`
`a.rotate(4, arr);`

I am getting following output: 
1
1	2	3

But I believe output should be :
1
2    3    1

**Comment by payamrastogi** [comment]
Thanks for pointing it out. I have started working on some other problem. So left it in the middle. It's not final solution
